# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d4b4b21d2225e83e46121a1d5b9e7501d11876ebd5b13f56e078dbd79993350e0b2ce49a71ac1d74a78643ca96f630ffb9e1b6613059b33dd1fdc9f24a555480

test:
  secret_key_base: e0dd3e7ae95ce9530fff52a0826588f0841136ec3ddd8c1a079a3db803568629281126f7d4ca2229e7310d86c5c00a660a76f789c6f6b890bdb91602dcfc258d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
